### ISSUE TITLE
Create Architecture for Applied AI version of SSF 2.1

### ISSUE THREAD

**Issue by MrDio** [MrDio/Smartphone-Sensing-Framework#10]

**Comment by MrDio** [comment]
AI should be integrated in data - folder

**Comment by apgeorg** [comment]
Maybe some general methods like loading graphs etc. should be in the data-folder. 
The output of each model must be handled individually. Further, if we use fix models like MobileNet we can integrate the whole detector/classificator also in the data-folder.

**Comment by apgeorg** [comment]
Additionally we need a camera folder + interface in the hardwareAdapter folder.

**Comment by apgeorg** [comment]
When an image is captured, we need to display the image itself and some results added to the image or not. So some widgets have to been added to the view and handled by the UiThread like visibility on/off.

**Comment by MrDio** [comment]
Agree with camera folder, do you have a prototype for it or need halp with Android-Code?
