### ISSUE TITLE
Concept of AI Tool-Chain for AI Applied

### ISSUE THREAD

**Issue by MrDio** [MrDio/Smartphone-Sensing-Framework#12]
AC: Ananconda, Jupyter, tensorflow, etc.

**Comment by apgeorg** [comment]
# **Training**
**List of packages for ML (python):** 
theano (optional)
keras  (if theano is not installed, only tf backend used)
tensorflow (if gpu: tensorflow-gpu)
h5py
sklearn
opencv
Pillow
scipy
pandas
numpy
jupyter (nice for code visualization, testing etc.)

**List for GPU accel.:**
cudnn 

# **Inference**
tensroflow

**Comment by MrDio** [comment]
@apgeorg Cool. Can you recommend a Docker with the Env on git which we could use for all students? Or do you have your own? @umadbro96 Should we also add the Android Dev IDE into a one Docker with the ML Stuff and handle one Docker to the students?
