### ISSUE TITLE
Manage Trainings-Hardware or Cloud via Prof at HSE

### ISSUE THREAD

**Issue by MrDio** [MrDio/Smartphone-Sensing-Framework#13]
AC: Graka Tesla from Melcher
AC: Graka GTX from Roessler
AC: TI 1080 Recher fro Schmidt
AC: Azure account 100 € /Team / Semester

**Comment by MrDio** [comment]
Roessler: We can use the GTX GraKas from the HSE. FollowUp Meeting with Apo and Roessler pending.

**Comment by apgeorg** [comment]
How we can access that HW ?
