### ISSUE TITLE
HowTo - Install and run an simple example

### ISSUE THREAD

**Issue by apgeorg** [MrDio/Smartphone-Sensing-Framework#14]
Hey Dimi, 
gibt es ein HowTo wie ich das Projekt auschecke und es auf meiner Linux Maschine mit Android Studio zum laufen  bekomme? Am besten mit einem einfachen Beispiel a la "Hello World". 

Mögliche Infos kann ich mir vorstellen beim HowTo:

- Genaue dependecies auflisten mit version (sdk > XX, ndk >XX, android-studio, etc. ), 
- Wie installiere ich diese (falls kompliziert)
- Wie baue ich es in Android-Studio
- Wie lass ich es im emulator laufen oder mit Gerät
- WIe entwickle ich eine einfach Applikation

Grüße 
Apo

**Comment by umadbro96** [comment]
Hey Apo, 
ich werde es demnächst auf Linux ausprobieren, um genaue Aussagen treffen zu können. 
Grundsätzlich gilt jedoch, wenn du Git und Android Studio SDK installiert hast : 

- [ ] Projekt mittels Git klonen: 
1. Klonen
git clone https://github.com/MrDio/Smartphone-Sensing-Framework.git
2. In das Verzeichnis wechseln
cd  Smartphone-Sensing-Framework/
3. Die richtige Branche auswählen
git checkout MMA@SSF2.0_AndroidStudio_2018

- [ ] Android Studio: 
1. Android Studio starten & "Open an existing Android(...)" auswählen. (Ist das mit git geklonte Projekt)
![how-to](https://user-images.githubusercontent.com/22766714/36934544-c9a39716-1eeb-11e8-952a-4559d37d5f62.png)
2. Dialog in Android Studio durchlaufen, d.h. alle Dependencies, die benötigt werden step-by-step installieren (Android Studio fragt nach allem)
3. Wenn gradle build erfolgreich war, den von Android mitgelieferten Emulator auswählen, um das Projekt zu starten.

Siehe auch in der Wiki unter : 
Projekt klonen : https://github.com/MrDio/Smartphone-Sensing-Framework/wiki/Building-with-Android-SDK

Emulator aus Android SDK starten ( MAC or Windows) : https://developer.android.com/studio/run/emulator.html
Emulator aus CMD starten "In case Linux" : https://developer.android.com/studio/run/emulator-commandline.html

PS.: Falls etwas zu unklar formuliert ist, einfach bitte nochmal anstupsen, dann mache ich einen ausführlicheren Guide mit step-by-step Bildern

Grüße 
Dimi

**Comment by apgeorg** [comment]
Danke, für das schnelle Feedback! Gebaut wird das richtig mit gradle! 
Wenn ich es laufen lassen will, bekomme ich die Auswahl mit 2 Emulatoren 
- Nexus 5 X API 24
- Test API 24
Ich wähle den Nexus und dann kommen folgende Fehler: 

2:29 PM	Emulator: [140018639492928]:ERROR:android/android-emu/android/qt/qt_setup.cpp:28:Qt library not found at /opt/android-sdk/emulator/lib64/qt/lib

2:29 PM	Emulator: Could not launch '/opt/android-sdk/emulator/qemu/linux-x86_64/qemu-system-i386': No such file or directory

2:29 PM	Emulator: Process finished with exit code 2

Ich muss noch checken, woher die Fehler kommen. Vllt hast du ne Ahnung?

Ich habe vorher mein SDK, NDK und das Studio aktualisiert. Kann es sein, dass die API 24 bei mir nicht installiert ist oder was so etwas?

Greetz

**Comment by ghost** [comment]
Hey Apo, 

Versuch mal in der "Project Structure" die fehlende API manuell zu installieren.
Normalerweise sollte dich Android Studio beim öffnen des Projekts automatisch zum installieren der APIs auffordern.

Grüße 
Dimi

**Comment by umadbro96** [comment]
Hey Apo,

habe das Aufsetzen der Entwicklungsoberfläche auf Linux durchgeführt. 
Es funktioniert soweit alles. Da es sich bei mir um Linux auf einer virtuellen Maschine handelt, besteht die Möglichkeit, den hauseigenen Emulator zu nutzen, nicht.

Stattdessen gibt es 2 Möglichkeiten: 
    - In Android SDK -> Build -> Build APK(s) -> die APK auf unabhängigem Emulator aufspielen und testen (z.B. Bluestacks : https://www.bluestacks.com/de/index.html)
    - Oder einen ARM Android Emulator installieren, der jedoch 10x langsamer ist --> Echtzeitfähigkeit verletzt.

Wenn du auf einer nicht virtuellen Maschine arbeitest und dein CPU VT-x oder SVM unterstützt, sollten eigentlich keine Probleme auftreten. 
Ich habe vorher Git, JDK und danach Android Studio auf Linux installiert. 

- [ ] Git: 
1. sudo apt-get install git
2. sudo apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386 lib32z1 libbz2-1.0:i386 (da 64-bit Linux)
    a. git clone https://github.com/MrDio/Smartphone-Sensing-Framework.git
    b. cd Smartphone-Sensing-Framework/
    c. git checkout MMA@SSF2.0_AndroidStudio_2018

- [ ] JDK: 
1. http://www.oracle.com/technetwork/java/javase/downloads/jdk9-downloads-3848520.html (jdk-9.0.4_linux-x64_bin.tar.gz)

- [ ] Android SDK
1. https://developer.android.com/studio/index.html (android-studio-ide-171.4443003-linux.zip)

2. Vorhandenes Projekt öffnen 
![1](https://user-images.githubusercontent.com/22766714/36946081-9594ecfa-1fb7-11e8-8c45-7d83b11fbe13.png)

3. Schritte durchlaufen und fehlende Dependencies step-by-step installieren ...
![2](https://user-images.githubusercontent.com/22766714/36946082-95b1fb7e-1fb7-11e8-8e06-1974042f741c.png)

4. Platform & Build tools installieren
![3](https://user-images.githubusercontent.com/22766714/36946083-95cd6026-1fb7-11e8-89b6-651ce91b4a1d.png)
![4](https://user-images.githubusercontent.com/22766714/36946084-95e81ee8-1fb7-11e8-92a9-a190868aca27.png)

5. Virtual Device erstellen
![5](https://user-images.githubusercontent.com/22766714/36946085-96046e40-1fb7-11e8-9d24-1d62adb6bd65.png)

Vielleicht besteht die Möglichkeit eine Neuinstallation der IDE bei dir. Das letzte Bild zeigt schon einen Fehler bei der Verwendung des Emulator auf einer virtuellen Maschine. Abhilfe dazu schaffen die 2 oben genannten Möglichkeiten

Gruß
Dimi

**Comment by umadbro96** [comment]
Hier die Variante mit "echtem" physikalischen Gerät über USB angeschlossen in Linux;
![222](https://user-images.githubusercontent.com/22766714/36946531-74200ae4-1fbe-11e8-84a2-e3a5f43d3372.png)

**Comment by apgeorg** [comment]
Hey Dimi, danke für die Infos! Ich benutze jedoch ArchLinux als natives System, das ist noch n bisschen anders als Ubuntu. Naja, ich hab es zum laufen bekommen - ohne Fehler. Was gefehlt hat, war der Emulator an sich iwie.. den hab ich über Android-Studio nachinstalliert. Dann gab es noch n Proble mit  i965.so.. Denn hab ich mit einem WA für ArchLinux gelöst was ich hier mal festhalte (gilt nur ab Android-Studio 3.0):
ln -sf /usr/lib/libstdc++.so.6* /opt/android-sdk/emulator/lib64/libstdc++/

**Comment by apgeorg** [comment]
Also der Emulator startet, ich seh nur "Black Screen". Ist das korrekt?

**Comment by ghost** [comment]
Wenn das Installieren des Emulators wirklich funktioniert hat, solltest du beim "run" des Projects die App starten.
Würde vorschlagen, wir machen das nochmal gemeinsam Schritt für Schritt. Oder du installierst Android Studio nochmal von vorne so wie beschrieben. Bedingung für das Funktionieren des AVD Android Virtual Devices ist dass dein CPU kvm bzw. Vt unterstützt.

(Btw. hast du ein Graphisches UI auf dein Archlinux installiert ? )

**Comment by apgeorg** [comment]
Ja, sollten wir machen. Ich habe Dio gefragt zwecks Gruppe einrichten über whatsapp oder so, dann ist die Kommunikation schneller und einfacher. 

Mein Arch hat gnome. 

Ja, also beim 2ten boot vom Emulator hab ich die App gesehn!!! RapidDisruption oder so. Super! 
Ich starte noch mit API 24 ist das ok? oder brauchen wir da update?

**Comment by ghost** [comment]
closed 👍
