### ISSUE TITLE
Evaluate Use Cases for Applied AI Lecture based on the TF Object Detection API

### ISSUE THREAD

**Issue by MrDio** [MrDio/Smartphone-Sensing-Framework#21]
https://becominghuman.ai/tensorflow-object-detection-api-basics-of-detection-7b134d689c75
https://becominghuman.ai/tensorflow-object-detection-api-basics-of-detection-2-2-28b348495eec

**Comment by apgeorg** [comment]
As mentioned in the articles, we will also use some  pre-trained models like MobileNet based on the COCO dataset. You can find an simple example of an inference pipeline in tensorflow on my [repo](https://github.com/apgeorg/traffic-light-detection-and-classification/blob/master/Traffic%20Light%20Detection.ipynb)
